services:
  postgres:
    container_name: postgres
    build: ./postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  stash-box:
    container_name: stash-box
    image: stashapp/stash-box:development
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    links:
      - postgres
    volumes:
      - ./config:/root/.stash-box
    labels:
      - traefik.http.routers.stash-box.rule=Host(`<DOMAIN>`)
      - traefik.http.routers.stash-box.tls=true
      - traefik.http.routers.stash-box.tls.certresolver=stash-box
      - traefik.port=9998

  traefik:
    container_name: traefik
    image: traefik:2.3
    restart: always
    ports:
      - 80:80
      - 443:443
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.docker=true"
      - "--certificatesResolvers.stash-box.acme.email=<EMAIL>"
      - "--certificatesResolvers.stash-box.acme.storage=/acme.json"
      - "--certificatesresolvers.stash-box.acme.tlschallenge=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /traefik/acme.json:/acme.json
